from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import List, Tuple

import cv2
import numpy as np
from svgpathtools import svg2paths2

Point = Tuple[float, float]


def sample_svg_paths(svg_path: Path, sample_step: float = 1.0) -> List[List[Point]]:
    """
    Read SVG paths and sample every segment into a polyline.
    Smaller sample_step = smoother curves, but more G-code.
    """
    paths, _attributes, _svg_attributes = svg2paths2(str(svg_path))
    polylines: List[List[Point]] = []

    for path in paths:
        if len(path) == 0:
            continue

        pts: List[Point] = []

        for segment in path:
            try:
                seg_len = max(float(segment.length(error=1e-4)), 0.001)
            except Exception:
                seg_len = 1.0

            num_samples = max(2, int(math.ceil(seg_len / sample_step)))

            for i in range(num_samples):
                t = i / (num_samples - 1)
                p = segment.point(t)
                pts.append((float(p.real), float(p.imag)))

        # Remove duplicate consecutive points
        cleaned: List[Point] = []
        for p in pts:
            if not cleaned:
                cleaned.append(p)
            else:
                x1, y1 = cleaned[-1]
                x2, y2 = p
                if abs(x2 - x1) > 1e-9 or abs(y2 - y1) > 1e-9:
                    cleaned.append(p)

        if len(cleaned) >= 2:
            polylines.append(cleaned)

    return polylines


def get_bounds(polylines: List[List[Point]]) -> Tuple[float, float, float, float]:
    xs = [x for poly in polylines for x, _ in poly]
    ys = [y for poly in polylines for _, y in poly]
    return min(xs), min(ys), max(xs), max(ys)


def scale_polylines(
    polylines: List[List[Point]],
    width_mm: float,
    height_mm: float,
    margin_mm: float,
    keep_aspect: bool = True,
) -> List[List[Point]]:
    """
    Scale SVG coordinates into machine mm coordinates.
    """
    if not polylines:
        return []

    min_x, min_y, max_x, max_y = get_bounds(polylines)
    src_w = max_x - min_x
    src_h = max_y - min_y

    if src_w == 0 or src_h == 0:
        raise ValueError("SVG bounds are invalid.")

    usable_w = width_mm - 2 * margin_mm
    usable_h = height_mm - 2 * margin_mm

    if keep_aspect:
        scale = min(usable_w / src_w, usable_h / src_h)
        scaled_w = src_w * scale
        scaled_h = src_h * scale
        offset_x = margin_mm + (usable_w - scaled_w) / 2.0
        offset_y = margin_mm + (usable_h - scaled_h) / 2.0
    else:
        scale_x = usable_w / src_w
        scale_y = usable_h / src_h
        offset_x = margin_mm
        offset_y = margin_mm

    result: List[List[Point]] = []
    for poly in polylines:
        new_poly: List[Point] = []
        for x, y in poly:
            x0 = x - min_x
            y0 = y - min_y

            if keep_aspect:
                x_mm = offset_x + x0 * scale
                y_mm = offset_y + y0 * scale
            else:
                x_mm = offset_x + x0 * scale_x
                y_mm = offset_y + y0 * scale_y

            # Flip Y for Cartesian CNC coordinates
            y_mm = height_mm - y_mm
            new_poly.append((x_mm, y_mm))
        result.append(new_poly)

    return result


def sort_polylines(polylines: List[List[Point]]) -> List[List[Point]]:
    """
    Simple nearest-neighbor ordering to reduce pen travel.
    Also reverses paths if that reduces travel distance.
    """
    if not polylines:
        return []

    remaining = [list(poly) for poly in polylines]
    ordered = [remaining.pop(0)]

    while remaining:
        last_x, last_y = ordered[-1][-1]

        best_idx = 0
        best_dist = float("inf")
        best_reverse = False

        for i, poly in enumerate(remaining):
            sx, sy = poly[0]
            ex, ey = poly[-1]

            d_start = (sx - last_x) ** 2 + (sy - last_y) ** 2
            d_end = (ex - last_x) ** 2 + (ey - last_y) ** 2

            if d_start < best_dist:
                best_dist = d_start
                best_idx = i
                best_reverse = False

            if d_end < best_dist:
                best_dist = d_end
                best_idx = i
                best_reverse = True

        chosen = remaining.pop(best_idx)
        if best_reverse:
            chosen.reverse()
        ordered.append(chosen)

    return ordered


def generate_gcode(
    polylines: List[List[Point]],
    draw_feed: int = 1500,
    travel_feed: int = 3000,
    pen_up_cmd: str = "M5",
    pen_down_cmd: str = "M3 S30",
    close_paths: bool = False,
) -> str:
    lines: List[str] = []

    lines.append("; Generated by svg_to_gcode.py")
    lines.append("G21 ; mm units")
    lines.append("G90 ; absolute positioning")
    lines.append(pen_up_cmd)
    lines.append(f"G0 F{travel_feed} X0 Y0")
    lines.append("")

    for poly in polylines:
        if len(poly) < 2:
            continue

        start_x, start_y = poly[0]
        lines.append(pen_up_cmd)
        lines.append(f"G0 F{travel_feed} X{start_x:.3f} Y{start_y:.3f}")
        lines.append(pen_down_cmd)

        for x, y in poly[1:]:
            lines.append(f"G1 F{draw_feed} X{x:.3f} Y{y:.3f}")

        if close_paths:
            first_x, first_y = poly[0]
            last_x, last_y = poly[-1]
            if abs(first_x - last_x) > 1e-9 or abs(first_y - last_y) > 1e-9:
                lines.append(f"G1 F{draw_feed} X{first_x:.3f} Y{first_y:.3f}")

        lines.append(pen_up_cmd)
        lines.append("")

    lines.append(pen_up_cmd)
    lines.append(f"G0 F{travel_feed} X0 Y0")
    lines.append("M2")

    return "\n".join(lines)


def save_preview(
    polylines: List[List[Point]],
    width_mm: float,
    height_mm: float,
    output_path: Path,
) -> None:
    """
    Save a simple preview PNG.
    """
    scale = 4  # pixels per mm
    w = int(width_mm * scale)
    h = int(height_mm * scale)
    img = np.ones((h, w, 3), dtype=np.uint8) * 255

    for poly in polylines:
        pts = []
        for x_mm, y_mm in poly:
            x_px = int(round(x_mm * scale))
            y_px = int(round((height_mm - y_mm) * scale))
            pts.append([x_px, y_px])

        if len(pts) >= 2:
            arr = np.array([pts], dtype=np.int32)
            cv2.polylines(img, [arr], isClosed=False, color=(0, 0, 0), thickness=1)

    cv2.imwrite(str(output_path), img)


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert SVG paths directly to G-code.")
    parser.add_argument("input_svg", type=Path, help="Input SVG path")
    parser.add_argument("output_gcode", type=Path, help="Output G-code path")

    parser.add_argument("--width", type=float, default=210.0, help="Canvas width in mm")
    parser.add_argument("--height", type=float, default=297.0, help="Canvas height in mm")
    parser.add_argument("--margin", type=float, default=10.0, help="Margin in mm")

    parser.add_argument("--sample-step", type=float, default=1.0, help="Curve sampling step in SVG units")
    parser.add_argument("--draw-feed", type=int, default=1500, help="Drawing feed rate")
    parser.add_argument("--travel-feed", type=int, default=3000, help="Travel feed rate")
    parser.add_argument("--pen-up", type=str, default="M5", help="Pen up command")
    parser.add_argument("--pen-down", type=str, default="M3 S30", help="Pen down command")
    parser.add_argument("--close-paths", action="store_true", help="Close each polyline back to start")
    parser.add_argument("--no-sort", action="store_true", help="Disable path sorting")
    parser.add_argument("--stretch", action="store_true", help="Stretch to fill area instead of keeping aspect ratio")
    parser.add_argument("--preview", type=Path, default=None, help="Optional preview PNG path")

    args = parser.parse_args()

    polylines = sample_svg_paths(args.input_svg, sample_step=args.sample_step)
    print(f"SVG polylines found: {len(polylines)}")

    if not polylines:
        raise ValueError("No drawable SVG paths found.")

    polylines = scale_polylines(
        polylines,
        width_mm=args.width,
        height_mm=args.height,
        margin_mm=args.margin,
        keep_aspect=not args.stretch,
    )

    if not args.no_sort:
        polylines = sort_polylines(polylines)

    gcode = generate_gcode(
        polylines,
        draw_feed=args.draw_feed,
        travel_feed=args.travel_feed,
        pen_up_cmd=args.pen_up,
        pen_down_cmd=args.pen_down,
        close_paths=args.close_paths,
    )

    args.output_gcode.write_text(gcode, encoding="utf-8")
    print(f"Saved G-code to: {args.output_gcode}")

    if args.preview is not None:
        save_preview(polylines, args.width, args.height, args.preview)
        print(f"Saved preview to: {args.preview}")


if __name__ == "__main__":
    main()